In [ ]:
# K-means算法时集简单和经典于一身的基于距离的聚类算法。采用距离作为相似度的评价指标，即认为两个对象的距离越近，其相似度就越大。该算法认为类簇是由距离靠近的对象组成的，因此把得到紧凑且独立的簇作为最终目标。

# 通过迭代寻找k个类簇的一种划分方案，使得用这k个类簇的均值来代表相应各类样本时所得的总体误差最小。

# k个聚类具有以下特点：各聚类本身尽可能的紧凑，而各聚类之间尽可能的分开。

# k-means算法的基础是最小误差平方和准则通过迭代寻找k个类簇的一种划分方案，使得用这k个类簇的均值来代表相应各类样本时所得的总体误差最小。

# k个聚类具有以下特点：各聚类本身尽可能的紧凑，而各聚类之间尽可能的分开。

# k-means算法的基础是最小误差平方和准则

In [ ]:
# k-means算法是将样本聚类成k个簇(cluster)，其中k是用户给定的，其求解过程非常直观简单，具体算法描述如下：

# 其伪代码如下：

# ********************************************************************

# 创建k个点作为初始的质心点（随机选择）

# 当任意一个点的簇分配结果发生改变时

#         对数据集中的每一个数据点

#                    对每一个质心

#                             计算质心与数据点的距离

#                    将数据点分配到距离最近的簇

#          对每一个簇，计算簇中所有点的均值，并将均值作为质心

# ********************************************************************

In [1]:
from numpy import *
#加载数据
def loadDataSet(fileName):
    dataMat = []
    fr = open(fileName)
    for line in fr.readlines():
        curLine = line.strip().split('\t')
        fltLine = map(float, curLine)    #变成float类型
        dataMat.append(fltLine)
    return dataMat

# 计算欧几里得距离
def distEclud(vecA, vecB):
    return sqrt(sum(power(vecA - vecB, 2)))

#构建聚簇中心，取k个(此例中为4)随机质心
def randCent(dataSet, k):
    n = shape(dataSet)[1]
    centroids = mat(zeros((k,n)))   #每个质心有n个坐标值，总共要k个质心
    for j in range(n):
        minJ = min(dataSet[:,j])
        maxJ = max(dataSet[:,j])
        rangeJ = float(maxJ - minJ)
        centroids[:,j] = minJ + rangeJ * random.rand(k, 1)
    return centroids

#k-means 聚类算法
def kMeans(dataSet, k, distMeans =distEclud, createCent = randCent):
    m = shape(dataSet)[0]
    clusterAssment = mat(zeros((m,2)))    #用于存放该样本属于哪类及质心距离
    centroids = createCent(dataSet, k)
    clusterChanged = True
    while clusterChanged:
        clusterChanged = False
        for i in range(m):
            minDist = inf; minIndex = -1
            for j in range(k):
                distJI = distMeans(centroids[j,:], dataSet[i,:])
                if distJI < minDist:
                    minDist = distJI; minIndex = j
            if clusterAssment[i,0] != minIndex: clusterChanged = True
            clusterAssment[i,:] = minIndex,minDist**2
        print(centroids)
        for cent in range(k):
            ptsInClust = dataSet[nonzero(clusterAssment[:,0].A == cent)[0]]   # 去第一列等于cent的所有列
            centroids[cent,:] = mean(ptsInClust, axis = 0)
    return centroids, clusterAssment

In [4]:
#################################################
# kmeans: k-means cluster
#################################################
from numpy import *
import time
import matplotlib.pyplot as plt
## step 1:加载数据
print("step 1: load data...")
dataSet = []
fileIn = open('/Users/lirawx/Documents/Workspace/data-analysis-algorithms/machine-algorithms-with-python/testSet.txt')
for line in fileIn.readlines():
    lineArr = line.strip().split(',')
    print(lineArr)
    dataSet.append([float(lineArr[0]), float(lineArr[1])])
## step 2: 聚类
print("step 2: clustering...")
dataSet = mat(dataSet)
k = 4
centroids, clusterAssment = kMeans(dataSet, k)
## step 3:显示结果
print("step 3: show the result...")
# showCluster(dataSet, k, centroids, clusterAssment)

step 1: load data...
['1.658985', '4.285136']
['-3.453687', '3.424321']
['4.838138', '-1.151539']
['-5.379713', '-3.362104']
['0.972564', '2.924086']
['-3.567919', '1.531611']
['0.450614', '-3.302219']
['-3.487105', '-1.724432']
['2.668759', '1.594842']
['-3.156485', '3.191137']
['3.165506', '-3.999838']
['-2.786837', '-3.099354']
['4.208187', '2.984927']
['-2.123337', '2.943366']
['0.704199', '-0.479481']
['-0.392370', '-3.963704']
['2.831667', '1.574018']
['-0.790153', '3.343144']
['2.943496', '-3.357075']
step 2: clustering...
[[-5.23734347  1.81127241]
 [ 4.45848671 -0.2218259 ]
 [ 0.46805874  2.886279  ]
 [ 2.68800477 -1.19162504]]
[[-3.63862433 -0.00647017]
 [ 3.63668775  1.250562  ]
 [-0.07048525  3.373933  ]
 [ 1.374289   -3.0204634 ]]
[[-3.8053935  -1.66356975]
 [ 3.63668775  1.250562  ]
 [-1.1486855   3.351865  ]
 [ 1.374289   -3.0204634 ]]
[[-3.88455167 -2.72863   ]
 [ 3.63668775  1.250562  ]
 [-1.49429029  3.09182871]
 [ 1.374289   -3.0204634 ]]
step 3: show the result...


NameError: name 'showCluster' is not defined